language: python
python:
  - "3.5.2"
# command to install dependencies
install:
  - pip3 install -r requirements.txt
script:
  # command to lint code
  - flake8 --config .flake8
  # command to generation skeleton extension
  - python3 setup_cython.py build_ext --inplace
  # command to run tests
  - nosetests --with-coverage --cover-erase --cover-package=skeleton,metrics,runscripts --cover-html

# operating system tested on
os: linux
